#define CONFIG_EBML_WRITING
#undef CONFIG_EBML_UNICODE
#define CONFIG_EBML_UNICODE
#define USE_PRECOMPILED_HEADERS
#cmakedefine CONFIG_DEBUGCHECKS
#cmakedefine CONFIG_STDIO
#cmakedefine CONFIG_DEBUG_LEAKS
